# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pm-model',
                'doc_host': 'https://jinhyukchoi.github.io',
                'git_url': 'https://github.com/jinhyukchoi/pm-model',
                'lib_path': 'pm_model'},
  'syms': {'pm_model.core': {'pm_model.core.foo': ('core.html#foo', 'pm_model/core.py')}}}
