"""Fill in a module description here

Docs: https://jinhyukchoi.github.io/pm-modelcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['foo']

# %% ../nbs/00_core.ipynb #151da945
def foo(): pass
